export const CONSTANTS={


    BASE_URL:'http://103.168.252.3:84',
    DEVICE_ID:987654321,

    GET_USER_REG:'USER_REG',
    GET_USER_REG_SUCCESS:'USER_REG_SUCCESS',
    GET_USER_REG_ERROR:'USER_REG_ERROR',

    GET_OTP_VERIFY:'OTP_VERIFY',
    GET_OTP_VERIFY_SUCCESS:'OTP_VERIFY_SUCCESS',
    GET_OTP_VERIFY_ERROR:'OTP_VERIFY_ERROR',

    GET_RESEND_OTP:'RESEND_OTP',
    GET_RESEND_OTP_SUCCESS:'RESEND_OTP_SUCCESS',
    GET_RESEND_OTP_ERROR:'RESEND_OTP_ERROR',

    GET_SAVE_PUNCH:'SAVE_PUNCH',
    GET_SAVE_PUNCH_SUCCESS:'SAVE_PUNCH_SUCCESS',
    GET_SAVE_PUNCH_ERROR:'SAVE_PUNCH_ERROR',

    GET_TODAY_ATTENDENCE:'TODAY_ATTENDENCE',
    GET_TODAY_ATTENDENCE_SUCCESS:'TODAY_ATTENDENCE_SUCCESS',
    GET_TODAY_ATTENDENCE_ERROR:'TODAY_ATTENDENCE_ERROR',
    
    GET_MONTHLY_ATTENDENCE:'MONTHLY_ATTENDENCE',
    GET_MONTHLY_ATTENDENCE_SUCCESS:'MONTHLY_ATTENDENCE_SUCCESS',
    GET_MONTHLY_ATTENDENCE_ERROR:'MONTHLY_ATTENDENCE_ERROR',


}